apiVersion: cloud.google.com/v1
kind: BackendConfig
# NOTE this backend config must be applied to the NodePort services in all 3 apps via annotations
metadata:
  name: my-backendconfig
spec:
  iap:
    enabled: true
    oauthclientCredentials:
      secretName: my-secret    

# sampleRate: Specify a value from 0.0 through 1.0, where 0.0 means no packets are logged 
# and 1.0 means 100% of packets are logged. This field is only relevant if enable is set 
# to true. sampleRate is an optional field, but if it's configured then enable: true must 
# also be set or else it is interpreted as enable: false.    